version: '3.8'

services:
  mongodb:
    image: docker.io/library/mongo:7.0
    container_name: pizza_orders_mongo
    restart: always
    ports:
      - '27017:27017'

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ''

    volumes:
      - mongo_data:/data/db


#  kafka:
#    image: confluentinc/cp-kafka:7.8.3
#    container_name: kafka
#    ports:
#      - "9092:9092"
#      - "29092:29092"
#
#    healthcheck:
#      test: [ "CMD-SHELL", "nc -z localhost 9092 || exit 1" ]
#      interval: 5s
#      timeout: 15s
#      retries: 10
#      start_period: 20s
#
#    environment:
#      KAFKA_KRAFT_MODE: 'true'
#
#      CLUSTER_ID: '1L6g7nGhU-eAKfL--X25wo'
#      KAFKA_NODE_ID: 1
#
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
##      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
##      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#
#      KAFKA_LOG_DIRS: /var/lib/kafka/data
#
#    volumes:
#      - kafka_kraft:/var/lib/kafka/data

  kafka:
      image: confluentinc/cp-kafka:7.8.3
      container_name: kafka
      ports:
        - "9092:9092"
        - "29092:29092"
      environment:
        KAFKA_NODE_ID: 1
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
        KAFKA_KRAFT_MODE: 'true'
        CLUSTER_ID: '1L6g7nGhU-eAKfL--X25wo'

        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT

        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093

        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_LOG_DIRS: /var/lib/kafka/data
      volumes:
        - kafka_kraft:/var/lib/kafka/data



  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092


  redis:
    image: redis:latest
    container_name: redis_orders
    ports:
      - '6441:6379'
#    healthcheck:
#      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

    volumes:
      - redis_data:/data


  redis_ui:
    image: redis/redisinsight:latest
    container_name: redis_orders_ui
    ports:
      - '5540:5540'
    depends_on:
      - redis


  api:
    build:
      context: /api
      dockerfile: Dockerfile

    environment:
      KAFKA_URI: 'kafka:9092'
      KAFKA_TOPIC: 'pizza-orders'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6441'
      MONGODB_COLLECTION: 'pizza_orders'
      MONGODB_DATABASE: 'pizza_orders'
      MONGO_URI: 'mongodb://root:password@mongodb:27017/?authSource=admin'

    ports:
      - '8001:8001'

    depends_on:
      - kafka
      - redis
      - mongodb


  worker_kitchen:
    build:
      context: /kitchen_consumer
      dockerfile: Dockerfile

    restart: always

    environment:
      KAFKA_TOPIC: 'pizza-orders'
      KAFKA_GROUP_ID: 'text-team'
      KAFKA_URI: "kafka:9092"
      REDIS_HOST: 'redis'
      REDIS_PORT: '6441'
      MONGODB_COLLECTION: 'pizza_orders'
      MONGODB_DATABASE: 'pizza_orders'
      MONGO_URI: 'mongodb://root:password@mongodb:27017/?authSource=admin'

    depends_on:
      - kafka
      - redis
      - mongodb


  worker_text:
    build:
      context: text_consumer
      dockerfile: Dockerfile

    environment:
      KAFKA_TOPIC: 'pizza-orders'
      KAFKA_GROUP_ID: 'kitchen-team'
      KAFKA_URI: "kafka:9092"
      MONGODB_COLLECTION: 'pizza_orders'
      MONGODB_DATABASE: 'pizza_orders'
      MONGO_URI: 'mongodb://root:password@mongodb:27017/?authSource=admin'

    depends_on:
      - kafka
      - mongodb


volumes:
  kafka_kraft:
  redis_data:
  mongo_data: